# Generated by Django 4.2.6 on 2023-10-10 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8, 'Tên người dùng ít nhất có 8 ký tự')])),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(8, 'Mật khẩu ít nhất có 8 ký tự')])),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
