# Generated by Django 4.2.6 on 2023-10-10 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8, 'Mật khẩu ít nhất có 8 ký tự')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8, 'Tên người dùng ít nhất có 8 ký tự')]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('content', models.TextField()),
                ('number_of_likes', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('age_restriction', models.CharField(choices=[('All', 0), ('18+', 18)], max_length=3)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.user')),
            ],
        ),
    ]
