# Generated by Django 4.2.6 on 2023-10-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('article_type', models.CharField(choices=[('Photog', 'Ảnh chụp'), ('Illust', 'Tranh vẽ')], max_length=6)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=1000)),
                ('age_restriction', models.CharField(choices=[('All', 0), ('18+', 18)], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(choices=[('Photog', 'Ảnh chụp'), ('Illust', 'Tranh vẽ')], max_length=6, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.user')),
                ('picture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.type')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.post', unique=True)),
                ('previous_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.user', unique=True)),
            ],
        ),
    ]
