# Generated by Django 4.2.6 on 2023-10-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_user_avater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avater',
            new_name='avatar',
        ),
    ]
