# Generated by Django 4.2.6 on 2023-10-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_rename_avater_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture_type',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.picture')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.post')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.article')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.picture')),
            ],
        ),
    ]
