# Generated by Django 4.2.6 on 2023-11-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_remove_postpicture_picture_remove_postpicture_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
