# Generated by Django 4.2.6 on 2023-11-27 04:54

import Project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_post_type_alter_article_article_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to=Project.models.post_image_path),
        ),
    ]
