# Generated by Django 4.2.6 on 2023-12-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_favouritepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritepost',
            name='contributor',
            field=models.IntegerField(null=True),
        ),
    ]
